# Generated by Django 4.1 on 2022-09-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.CharField(max_length=50, verbose_name='Группа товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Вид товара'),
        ),
    ]
