# Generated by Django 4.1 on 2022-09-09 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_item_group_alter_item_name_alter_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='uuid_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
