# Generated by Django 4.1 on 2022-09-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_item_uuid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
